apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_HOST: {{ .Values.secrets.database.host }}
  DB_NAME: {{ .Values.secrets.database.name }}
  DB_PORT: "{{ .Values.secrets.database.port }}"  
  DB_USERNAME: {{ .Values.secrets.database.username }}
  DB_PASSWORD: {{ .Values.secrets.database.password }}
