namespace: online-shop
replicas: 2
labels: online-shop-backkend

image: viettu123/online-shop-backend:pipeline-be-eks_v1_eb4252a4 

container:
  Port: 5214

service:
  Port: 31000

configMap:
  name: online-shop-backend-application-properties-configmap

volumes:
  name: ecommerce-backend-application-properties-config-volume

volumeMounts:
  mountPath: /app/appsettings.json
  subPath: appsettings.json


secrets:
  name: online-shop-backend-database-connection
  database:
    host: "sqlserver-0.sqlserver.default.svc.cluster.local"
    name: "OnlineShopdb"
    port: "1433"
    username: "sa"
    password: "Str0ngPa5sVvorcl"