apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "common.labels" . | nindent 6 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels: {{ include "common.labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "common.labels" . | nindent 8 }}
      namespace: {{ .Values.namespace }}
    spec:
      containers:
        - image: {{ .Values.image }}
          imagePullPolicy: Always
          env:
          - name: BackEnd_URL
            value: {{ .Values.BackEnd_URL }}
          ports:
            - containerPort: {{ .Values.container.Port }}
              name: tcp
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits: 
              memory: "128Mi"
              cpu: "500m"
