apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
data:
  appsettings.json: |
    {
      "ConnectionStrings": {
        "UserAppCon": "Server=${DB_HOST},${DB_PORT};Database=${DB_NAME};User Id=${DB_USERNAME};Password=${DB_PASSWORD}"
      },
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "Jwt": {
        "Secret": "your_secret_key_here"
      },
      "AllowedHosts": "*"
    }

