apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp
      port: {{ .Values.container.Port }}
      protocol: TCP
      targetPort: {{ .Values.container.Port }}
  selector: {{ include "common.labels" . | nindent 6 }}
  sessionAffinity: None
  type: ClusterIP