FROM ubuntu:latest

RUN apt update -y && apt instll -y wget tar && rm -rf /var/lib/apt/lists/*
RUN  wget https://github.com/Arachni/arachni/releases/download/v1.6.1.3/arachni-1.6.1.3-0.6.1.1-linux-x86_64.tar.gz && rm arachni-1.6.1.3-0.6.1.1-linux-x86_64.tar.gz

WORKDIR arachni-1.6.1.3-0.6.1.1

CMD ["bin/arachni"]